# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iHGT9-clGjZU5BkE9biQFtJK7iNyhh9F
"""

a=int(input("Enter a number: "))
if(a%2==0):
  print("Even")
else:
  print("Odd")

